---
abstract: 'HTML5 application cache manifest file generator for Module::Install'
author:
  - 'Kazuhiro Osawa <yappo {at} shibuya {dot} pl>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-HTML5Manifest
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Dumper: 0
  HTML5::Manifest: 0
  MIME::Base64: 0
  Module::Install: 0
resources:
  homepage: http://github.com/yappo/p5-Module-Install-HTML5Manifest/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yappo/p5-Module-Install-HTML5Manifest.git
version: 0.01_01
